#config_version=6

ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_one, s_ball_trough_two, s_ball_trough_three, s_ball_trough_four, s_ball_trough_five, s_ball_trough_six, s_ball_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_ball_trough_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger
        eject_timeouts: 3s
        # bd_plunger is a placeholder just so the trough's eject_targets are valid
    bd_plunger:
        ball_switches: s_plunger_lane
        mechanical_eject: true
#    bd_scoop:
#        ball_switches: s_scoop
#        eject_coil: c_scoop_eject
#        eject_timeouts: 1s
#    bd_left_saucer
#        ball_switches: s_left_saucer
#        eject_coil: c_left_saucer_eject
#        eject_timeouts: 1s
#    bd_right_saucer
#        ball_switches: s_right_saucer
#        eject_coil: c_right_saucer_eject
#        eject_timeouts: 1s