#config_version=6

#lights:
#   name_of_led:
#       number: playfield_exp_board-1-9      # board name / port 1 / 9th led in the chain

lights:
    ride_again:
        number:
    shag_s:
        number:
    shag_h:
        number:
    shag_a:
        number:
    shag_g:
        number:
    lightning_1:
        number:
    lightning_2:
        number:
    lightning_3:
        number:
    lightning_4:
        number:
    snow_rider_achievement:
        number:
    shibby_achievement:
        number:
    credit_card_roulette:
        number:
    t_bar_teddy:
        number:
    mauve_manther:
        number:
    chinese_downhill:
        number:
    sharks_in_the_water:
        number:
    ass_on_the_glass:
        number:
    full_colin:
        number:
    blueberry_yeti:
        number:
    jack:
        number:
    ted:
        number:
    art:
        number:
    guy:
        number:
    klaus:
        number:
    squirrel:
        number:
    colin:
        number:
    jimmy:
        number:
    shag:
        number:
    dave:
        number:
    room35_r:
        number:
    room35_o:
        number:
    room35_oo:
        number:
    room35_m:
        number:
    room35_3:
        number:
    room35_5:
        number:
    klaus_k:
        number:
    klaus_l:
        number:
    klaus_a:
        number:
    klaus_u:
        number:
    kalus_s:
        number:
    squirrel_disc:
        number:
    left_lane_arrow:
        number:
    left_orbit_arrow:
        number:
    left_ramp_arrow:
        number:
    center_lane_arrow:
        number:
    beer_target_arrow:
        number:
    scoop_arrow:
        number:
    right_ramp_arrow:
        number:
    right_orbit_arrow:
        number:
    lava:
        number:
    extra_ball:
        number:
    room_35_multiball:
        number:
    load_snow_riders:
        number:
    heli_multiball:
        number:
    shibby:
        number:
    collect_nuts:
        number:
    squirrel_multiball:
        number:
    tbar_t:
        number:
    tbar_b:
        number:
    tbar_a:
        number:
    tbar_r:
        number:
    secret_stash:
        number:
    mode_start:
        number:
    guy_g:
        number:
    guy_u:
        number:
    guy_y:
        number:
    downhillium:
        number:
    rider_1:
        number:
    rider_2:
        number:
    rider_3:
        number:
    rider_4:
        number:
    manther_m:
        number:
    manther_a:
        number:
    manther_n:
        number:
    manther_t:
        number:
    manther_h:
        number:
    manther_e:
        number:
    manther_r:
        number: